# .github/workflows/_lint.yml
name: Lint

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: lint checks with fmt and clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
